### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Nitrogenycs** [kragniz/python-etcd3#291]
Repeatedly calling etcd3.client(...) in a loop will leak lots of memory over time. The main reasons seems to be that this creates a watcher thread every time. This thread is never stopped or deleted thus causing memory to grow without bounds.

**Comment by wjun** [comment]
I also meet this issue and can get thousands of threads in one day or two. After I disable watcher creations, the number of threads and etcd connections get stable.

**Comment by joelazar** [comment]
I think it's solved now. I've tried this out with the latest version (0.8.0) and didn't experienced memory/thread leaking.

**Comment by enadam** [comment]
No it's not completely solved.  When Watcher._run() receives a grpc.RpcError because of a connection break the thread doesn't stop.  With certain versions of grpcio the thread starts consuming 100% CPU.  The solution is simple: add a break statement after the callback invocations.
[patch.txt](https://github.com/kragniz/python-etcd3/files/3672417/patch.txt)
